import type { MessageKey } from './zh-CN';

/** 英文文案：必须覆盖 zh-CN 的全部 key（类型由 MessageKey 保证） */
export const enUS: Record<MessageKey, string> = {
  // ---- 应用 ----
  'app.name': 'Zhishu · Intelligent Business Platform',
  'app.shortName': 'Zhishu',

  // ---- 导航 ----
  'nav.group.ai': 'AI Assistant',
  'nav.home': 'Home',
  'nav.formBuilder': 'Form Builder',
  'nav.formRenderer': 'Form Renderer',
  'nav.settlePool': 'Settlement Pool',
  'nav.chat': 'AI Chat',
  'nav.deepseekChat': 'DeepSeek Chat',
  'nav.hint.chat': 'CopilotKit agent that can operate business modules',
  'nav.hint.deepseekChat': 'Direct DeepSeek model, pure chat',

  // ---- 全局 AI 助手 ----
  'assistant.open': 'Open AI assistant',
  'assistant.close': 'Hide AI assistant',

  // ---- DeepSeek 对话页 ----
  'deepseek.status.checking': 'Checking…',
  'deepseek.status.ready': 'Ready',
  'deepseek.status.unconfigured': 'Key missing',
  'deepseek.status.offline': 'Disconnected',
  'deepseek.statusTip': 'Service status: {status}',
  'deepseek.modelSelect': 'Select model',
  'deepseek.regenerate': 'Regenerate',
  'deepseek.regenerateTip': 'Regenerate the last reply',
  'deepseek.clear': 'Clear',
  'deepseek.clearTip': 'Clear the whole conversation',
  'deepseek.error.invalidKey':
    'Invalid or missing model key. Set DEEPSEEK_API_KEY in .env and restart the service.',
  'deepseek.error.offline': 'Cannot reach the backend proxy. Make sure the service is running.',
  'deepseek.error.generic': 'Generation failed, please try again.',
  'deepseek.error.streamUnsupported': 'Streaming not supported (response.body is empty)',
  'deepseek.input.placeholder': 'Message DeepSeek…',
  'deepseek.input.stop': 'Stop',
  'deepseek.input.stopTip': 'Stop generating',
  'deepseek.input.send': 'Send',
  'deepseek.input.hint.unconfigured': 'No model key configured, AI cannot reply',
  'deepseek.input.hint.offline': 'Proxy is not running, start the service first',
  'deepseek.input.hint.normal': 'Content is generated by DeepSeek and may be inaccurate',
  'deepseek.welcome.title': 'Hi, I am the DeepSeek assistant',
  'deepseek.welcome.sub':
    'This page talks to DeepSeek through a local proxy, with streaming and chain-of-thought.',
  'deepseek.sample.1': 'Explain HTTP caching in one sentence',
  'deepseek.sample.2': 'Write a TypeScript debounce function and explain how to use it',
  'deepseek.sample.3': 'Break this requirement into tasks: build a report export feature',
  'deepseek.sample.4': 'Introduce concurrent rendering in React',
  'deepseek.notice.close': 'Close',
  'deepseek.notice.unconfigured':
    'No model key detected. Set DEEPSEEK_API_KEY in .env and restart the service.',
  'deepseek.notice.offline': 'The backend proxy is not connected, start the service and',
  'deepseek.model.chat': 'DeepSeek V3',
  'deepseek.model.chatHint': 'General chat, fast',
  'deepseek.model.reasoner': 'DeepSeek R1',
  'deepseek.model.reasonerHint': 'Deep reasoning with chain-of-thought',
  'deepseek.announce': 'New: streaming output and R1 deep thinking (chain-of-thought). Feedback welcome →',
  'deepseek.hero.title': 'Explore the unknown',
  'deepseek.thinking.active': 'Thinking…',
  'deepseek.thinking.done': 'Thought for {seconds} seconds',
  'deepseek.action.copy': 'Copy',
  'deepseek.action.copied': 'Copied',
  'deepseek.action.copyTip': 'Copy all',
  'deepseek.action.likeTip': 'Like',
  'deepseek.action.dislikeTip': 'Dislike',
  'deepseek.failed': 'Generation failed. Check the backend proxy and key config, then retry.',
  'deepseek.pill.chat': 'V3 Chat',
  'deepseek.pill.reasoner': 'Deep Think',
  'deepseek.toBottom': 'Back to bottom',
  'deepseek.attach.add': 'Add image',
  'deepseek.attach.remove': 'Remove',
  'deepseek.attach.alt': 'Attachment {index}',
  'deepseek.attach.tip': 'The model cannot read images; they are shown with your message only',
  'deepseek.attach.limit': 'Up to {max} images',
  'deepseek.attach.tooLarge': 'Image must be under {size}MB',
  'deepseek.preview.close': 'Click to close preview',
  'deepseek.outline': 'Questions',

  // ---- 404 ----
  'notFound.desc': 'Sorry, the page you visited does not exist or has been removed.',
  'notFound.backHome': 'Back to home',

  // ---- 语言 ----
  'locale.label': 'Language',
  'locale.zh-CN': '简体中文',
  'locale.en-US': 'English',

  // ---- 通用 ----
  'common.retry': 'Retry',
  'common.loading': 'Loading…',
  'common.error': 'Something went wrong',
};
